<?php

require_once '../vendor/autoload.php';

use koenster\PHPGraphs\PHPChart;

$chart = new PHPChart($type);

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>PHP Graphs - <?php echo $type; ?></title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<?php foreach ($chart->getFactory()->getCss() as $css) : ?>
    <link rel="stylesheet" href="<?php echo $css; ?>">
<?php endforeach; ?>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<?php foreach ($chart->getFactory()->getJs() as $js) : ?>
    <script src="<?php echo $js; ?>"></script>
<?php endforeach; ?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.php">PHP Graphs</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li <?php if ($type === 'ChartJS') : ?> class="active" <?php endif; ?>><a href="index.php">ChartJS</a></li>
                    <li <?php if ($type === 'MorrisJS') : ?> class="active" <?php endif; ?>><a href="morris-js.php">MorrisJS</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <div class="container">
        <h1 class="page-header">ChartJS</h1>
        <h2>Installation</h2>
        <p>
            Require this package with composer:
        </p>
        <pre>composer require koenster/php-graphs</pre>
        <p>
            You can choose to either add the js / css files in your template by the graph php object or you can implement it your self.
        </p>
        <pre>
&#x3C;!doctype html&#x3E;
&#x3C;html&#x3E;
&#x3C;head&#x3E;
    &#x3C;!-- This is optional --&#x3E;
    &#x3C;?php foreach ($chart-&#x3E;getFactory()-&#x3E;getCss() as $css) : ?&#x3E;
    &#x3C;link rel=&#x22;stylesheet&#x22; href=&#x22;&#x3C;?php echo $css; ?&#x3E;&#x22;&#x3E;
    &#x3C;?php endforeach; ?&#x3E;

    &#x3C;!-- This is optional --&#x3E;
    &#x3C;?php foreach ($chart-&#x3E;getFactory()-&#x3E;getJs() as $js) : ?&#x3E;
    &#x3C;script src=&#x22;&#x3C;?php echo $js; ?&#x3E;&#x22;&#x3E;&#x3C;/script&#x3E;
    &#x3C;?php endforeach; ?&#x3E;
&#x3C;/head&#x3E;
&#x3C;body&#x3E;

...

&#x3C;script&#x3E;
    // This will gather all charts and activate the JS library to convert the provided JSON to a Graph
    &#x3C;?php echo $chart-&#x3E;getFactory()-&#x3E;getJsPartial(); ?&#x3E;
&#x3C;/script&#x3E;
&#x3C;/html&#x3E;
        </pre>

        <div class="alert alert-info">Take a close look at the last lines. In order to convert all json objects (generated by the libary) to graphs, the correct javascript snipped need to be included within your page.</div>
        <br /><br />

        <h2 id="line-chart">Line chart</h2>
<?php
try {
    $graph = $chart->add(PHPChart::TYPE_LINE, 'Line', ['width' => '100%', 'height' => 400]);
    $graph->setLine([100, 75, 50, 75, 50, 75, 100], ['label' => 'Series A'])
        ->setLine([90, 65, 40, 65, 40, 65, 150], ['label' => 'Series B'])
        ->setDimensions(['2006', '2007', '2008', '2009', '2010', '2011', '2012']);

    $graph->generate();
?>

        <div class="row">
            <div class="col-md-6">

                <?php echo $graph->generate(); ?>

            </div>
            <div class="col-md-6">
                <pre>
use koenster\PHPGraphs\PHPChart;

$chart = new PHPChart(<?php echo $implementation; ?>);

$graph = $chart->add(PHPChart::TYPE_LINE, 'Line', ['width' => '100%', 'height' => 400]);
$graph->setLine([100,75,50,75,50,75,100], ['label' => 'Series A'])
    ->setLine([90,65,40,65,40,65,150], ['label' => 'Series B'])
    ->setDimensions(['2006', '2007', '2008', '2009', '2010', '2011', '2012']);

echo $graph->generate();
                </pre>
            </div>
        </div>

<?php
} catch (\Exception $e) {
?>

        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">
                    This chart type is not supported within this implementation.
                </div>
            </div>
        </div>

<?php
}
?>
        <!-- /#line-chart -->
        <br /><br />
        <h2 id="area-chart">Area chart</h2>
<?php
try {
    $graph = $chart->add(PHPChart::TYPE_AREA, 'Area', ['width' => '100%', 'height' => 400]);
    $graph->setLine([100, 75, 50, 75, 50, 75, 100], ['label' => 'Series A'])
        ->setLine([90, 65, 40, 65, 40, 65, 150], ['label' => 'Series B'])
        ->setDimensions(['2006', '2007', '2008', '2009', '2010', '2011', '2012']);

    $graph->generate();
?>

        <div class="row">
            <div class="col-md-6">

                <?php echo $graph->generate(); ?>

            </div>
            <div class="col-md-6">
                <pre>
use koenster\PHPGraphs\PHPChart;

$chart = new PHPChart(<?php echo $implementation; ?>);

$graph = $chart->add(PHPChart::TYPE_AREA, 'Area', ['width' => '100%', 'height' => 400]);
$graph->setLine([100,75,50,75,50,75,100], ['label' => 'Series A'])
    ->setLine([90,65,40,65,40,65,150], ['label' => 'Series B'])
    ->setDimensions(['2006', '2007', '2008', '2009', '2010', '2011', '2012']);

echo $graph->generate();
                </pre>
            </div>
        </div>

<?php
} catch (\Exception $e) {
?>

        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">
                    This chart type is not supported within this implementation.
                </div>
            </div>
        </div>

<?php
}
?>
        <!-- /#area-chart -->
        <br /><br />
        <h2 id="radar-chart">Radar chart</h2>
<?php
try {
    $graph = $chart->add(PHPChart::TYPE_RADAR, 'Radar', ['width' => '100%', 'height' => 400]);
    $graph->setLine([100, 75, 50, 75, 50, 75, 100], ['label' => 'Series A'])
        ->setLine([90, 65, 40, 65, 40, 65, 150], ['label' => 'Series B'])
        ->setDimensions(['2006', '2007', '2008', '2009', '2010', '2011', '2012']);

    $graph->generate();
?>

        <div class="row">
            <div class="col-md-6">

                <?php echo $graph->generate(); ?>

            </div>
            <div class="col-md-6">
                <pre>
use koenster\PHPGraphs\PHPChart;

$chart = new PHPChart(<?php echo $implementation; ?>);

$graph = $chart->add(PHPChart::TYPE_RADAR, 'Radar', ['width' => '100%', 'height' => 400]);
$graph->setLine([100,75,50,75,50,75,100], ['label' => 'Series A'])
    ->setLine([90,65,40,65,40,65,150], ['label' => 'Series B'])
    ->setDimensions(['2006', '2007', '2008', '2009', '2010', '2011', '2012']);

echo $graph->generate();
                </pre>
            </div>
        </div>

<?php
} catch (\Exception $e) {
?>

        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">
                    This chart type is not supported within this implementation.
                </div>
            </div>
        </div>

<?php
}
?>
        <!-- /#radar-chart -->
        <br /><br />
        <h2 id="bar-chart">Bar chart</h2>
<?php
try {
    $graph = $chart->add(PHPChart::TYPE_BAR, 'Radar', ['width' => '100%', 'height' => 400]);
    $graph->setLine([100, 75, 50, 75, 50, 75, 100], ['label' => 'Series A'])
        ->setLine([90, 65, 40, 65, 40, 65, 150], ['label' => 'Series B'])
        ->setDimensions(['2006', '2007', '2008', '2009', '2010', '2011', '2012']);

    $graph->generate();
?>

        <div class="row">
            <div class="col-md-6">

                <?php echo $graph->generate(); ?>

            </div>
            <div class="col-md-6">
                <pre>
use koenster\PHPGraphs\PHPChart;

$chart = new PHPChart(<?php echo $implementation; ?>);

$graph = $chart->add(PHPChart::TYPE_RADAR, 'Radar', ['width' => '100%', 'height' => 400]);
$graph->setLine([100,75,50,75,50,75,100], ['label' => 'Series A'])
    ->setLine([90,65,40,65,40,65,150], ['label' => 'Series B'])
    ->setDimensions(['2006', '2007', '2008', '2009', '2010', '2011', '2012']);

echo $graph->generate();
                </pre>
            </div>
        </div>

<?php
} catch (\Exception $e) {
?>

        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">
                    This chart type is not supported within this implementation.
                </div>
            </div>
        </div>

<?php
}
?>
        <!-- /#bar-chart -->
        <br /><br />
        <h2 id="pie-chart">Pie chart</h2>
<?php
try {
    $graph = $chart->add(PHPChart::TYPE_PIE, 'Pie', ['width' => 400, 'height' => 400]);
    $graph->setLine([41], ['label' => 'Series A'])
        ->setLine([231], ['label' => 'Series B'])
        ->setLine([451], ['label' => 'Series C']);

    $graph->generate();
?>

        <div class="row">
            <div class="col-md-6">

                <?php echo $graph->generate(); ?>

            </div>
            <div class="col-md-6">
                <pre>
use koenster\PHPGraphs\PHPChart;

$chart = new PHPChart(<?php echo $implementation; ?>);

$graph = $chart->add(PHPChart::TYPE_PIE, 'Pie', ['width' => 400, 'height' => 400]);
$graph->setLine([41], ['label' => 'Series A'])
    ->setLine([231], ['label' => 'Series B'])
    ->setLine([451], ['label' => 'Series C']);

echo $graph->generate();
                </pre>
            </div>
        </div>

<?php
} catch (\Exception $e) {
?>

        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">
                    This chart type is not supported within this implementation.
                </div>
            </div>
        </div>

<?php
}
?>
        <!-- /#pie-chart -->
        <br /><br />
        <h2 id="doughnut-chart">Doughnut chart</h2>
<?php
try {
    $graph = $chart->add(PHPChart::TYPE_DOUGHNUT, 'Doughnut', ['width' => 400, 'height' => 400]);
    $graph->setLine([41], ['label' => 'Series A'])
        ->setLine([231], ['label' => 'Series B'])
        ->setLine([451], ['label' => 'Series C']);

    $graph->generate();
?>

        <div class="row">
            <div class="col-md-6">

                <?php echo $graph->generate(); ?>

            </div>
            <div class="col-md-6">
                <pre>
use koenster\PHPGraphs\PHPChart;

$chart = new PHPChart(<?php echo $implementation; ?>);

$graph = $chart->add(PHPChart::TYPE_DOUGHNUT, 'Doughnut', ['width' => 400, 'height' => 400]);
$graph->setLine([41], ['label' => 'Series A'])
    ->setLine([231], ['label' => 'Series B'])
    ->setLine([451], ['label' => 'Series C']);

echo $graph->generate();
                </pre>
            </div>
        </div>

<?php
} catch (\Exception $e) {
?>

        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-danger">
                    This chart type is not supported within this implementation.
                </div>
            </div>
        </div>

<?php
}
?>
        <!-- /#pie-chart -->
        <br /><br />
    </div>

    <footer style="background: #fefefe; border-top: 1px solid #efefef; padding: 20px;">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <p>This PHP Graph library is open-sourced software licensed under the MIT license.</p>
                    <p>A project by <a href="http://koenbloklandvisser.nl">Koen Blokland Visser</a></p>
                </div>
            </div>
        </div>
    </footer>

    <script>
        <?php echo $chart->getFactory()->getJsPartial(); ?>
    </script>



</body>
</html>